In [1]:
import numpy as np

# Why Numpy?

* it is a primary package for scientific computing
* it supports multi-dimensional arrays 
* built in array operations
* Simplified but powerful array interactions

* Numpy arrays are fast 
* it can hold only one data type 


Pandas are built on top of numpy 

In [21]:
# working with ndarrays 
an_array = np.array([3,33,333]) # rank 1 array
print(an_array)
print(type(an_array))
print(an_array.shape) # printing shape of nd array

[  3  33 333]
<class 'numpy.ndarray'>
(3,)


## ndarrays are mutable

In [7]:
an_array[0]=20 # must be of the same type

In [9]:
r2 = np.array([[11,12,13],[14,15,16]])
r2

array([[11, 12, 13],
       [14, 15, 16]])

In [23]:
# creating prefilling arrays
ex1 = np.zeros((2,2))
ex2 = np.full((2,2),9) # creating a 2*2 array filled with 9
ex3 = np.ones((2,2))
ex4 = np.eye(2,2) # here only the diagonals are one 
ex5 = np.random.random((2,2))
ex5

array([[0.84035697, 0.68318669],
       [0.95497046, 0.89357235]])

In [27]:
# when slicing an ndarray we create a second reference to the same underlying data
a_slice  = r2[0:,1:2]
a_slice # when you modify the slice you are actually modifying the actual r2 array

array([[12],
       [15]])

## Since slice elements have the same memory address as the original array. we must create another copy to prevent this

In [28]:
a_slice  = np.array(r2[0:,1:2])
a_slice

array([[12],
       [15]])

In [31]:
#combinations of slices and indexing 
a_slice2 = r2[1,:] # this creates a rank1 array
a_slice3 = r2[1:2,:] # this creates a rank2 array
print(a_slice3)


[[14 15 16]]


In [32]:
r2.shape

(2, 3)